service: yukiyan-service

provider:
  name: aws
  runtime: nodejs4.3
  region: ap-northeast-1
  memorySize: 128
  timeout: 300
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "autoscaling:*"
      Resource:
        Fn::Join:
          - ""
          - - "*"
    - Effect: "Allow"
      Action:
        - "ecs:*"
      Resource:
        Fn::Join:
          - ""
          - - "*"
    - Effect: "Allow"
      Action:
        - "lambda:*"
      Resource:
        Fn::Join:
          - ""
          - - "*"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        Fn::Join:
          - ""
          - - "*"
package:
 exclude:
   - .envrc
   - .eslintignore
   - .eslintrc.js
   - .git
   - .npmignore
   - LICENSE
   - README.md
   - node_modules
   - package.json
   - yarn.lock

functions:
  hello:
    handler: src/handler.hello
  polling:
    handler: src/polling.polling
    events:
      - s3:
          bucket: polling
          event: s3:ObjectCreated:*
